version: 2

project_name: statusline

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/statusline
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.build={{.Date}}
    binary: statusline

archives:
  - id: statusline
    name_template: >-
     {{.ProjectName}}_
     {{- .Tag}}_
     {{- if eq .Os "darwin"}}macos
     {{- else if eq .Os "windows"}}win
     {{- else}}{{.Os}}{{end}}_
     {{- if eq .Arch "amd64"}}x86_64
     {{- else if eq .Arch "386"}}i386
     {{- else}}{{.Arch}}{{end}}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: unwnu
    name: statusline
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Changes

    This release includes the following updates:

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

universal_binaries:
  - replace: true